import { Experience, Skill, Project, ProfileData, Education, Certification, GitHubStats } from '@/types'

export const profile: ProfileData = {
  id: 1,
  name: 'Muhammad Rizki Putra',
  title: 'Senior Software Engineer | Kotlin | Go | Stockbit',
  location: 'Kota Tangerang Selatan, Banten, Indonesia',
  email: 'rzk.putra@gmail.com',
  linkedin: 'https://www.linkedin.com/in/muhammad-rizky-putra/',
  github: 'https://github.com/Rockerdx',
  summary: 'Seasoned Software Engineer with 5+ years of hands-on experience. Currently excelling as a Backend Engineer at Stockbit, specializing in Go development. Previously made significant contributions to Android development—improving app reliability and teaching Android classes at Binar Academy.',
  avatarUrl: 'https://avatars.githubusercontent.com/u/16275342?v=4',
}

export const experiences: Experience[] = [
  {
    id: 1,
    company: 'Stockbit',
    position: 'Backend Engineer',
    period: 'August 2023 - Present',
    duration: '2 years 9 months',
    location: 'Jakarta, Indonesia',
    achievements: [
      'Improved latency of core issuer/company RPC service by 80% using in-memory caching (Redis), reducing response time from 250ms to 50ms',
      'Optimized watchlist portfolio sync flow, handling 500,000 events per minute (watchlist is loaded every time 1M+ users open the app homepage)',
      'Implemented KV2 config scheme for secure credentials handling, dynamic configuration updates, and versioning across all financial services',
      'Designed complete migration plan to transition issuer symbol system to Indonesia Stock Exchange (IDX) as source of truth, coordinating with financial teams',
    ],
    techStack: ['Golang', 'PostgreSQL', 'gRPC', 'Microservices', 'Redis', 'Kafka', 'Docker', 'Kubernetes'],
  },
  {
    id: 2,
    company: 'Stockbit',
    position: 'Android Engineer',
    period: 'October 2021 - September 2023',
    duration: '2 years',
    location: 'Jakarta, Indonesia',
    achievements: [
      'Created a custom base view for rounded designs',
      'Enhanced app reliability, reducing Out Of Memory (OOM) incidents by 5% for older devices',
      'Boosted app render, layout drawing, and thread usage efficiency by 10-30%',
    ],
    techStack: ['Kotlin', 'Android', 'Java'],
  },
  {
    id: 3,
    company: 'Binar Academy',
    position: 'Android Academy Facilitator',
    period: 'April 2022 - August 2022',
    duration: '5 months',
    location: 'Jakarta, Indonesia',
    achievements: [
      'Facilitated Android classes, aiding non-tech individuals in kickstarting their careers as Android Engineers',
    ],
    techStack: ['Android', 'Kotlin', 'Java'],
  },
  {
    id: 4,
    company: 'Otospector',
    position: 'Senior Android Developer',
    period: 'March 2021 - September 2021',
    duration: '7 months',
    location: 'North Jakarta, Indonesia',
    achievements: [
      'Initiated and developed a new app for Otospector',
      'Maintained internal apps (Otoinspect)',
    ],
    techStack: ['Android', 'Kotlin'],
  },
  {
    id: 5,
    company: 'YesDok',
    position: 'Android Developer',
    period: 'August 2020 - March 2021',
    duration: '8 months',
    location: 'Jakarta, Indonesia',
    achievements: [
      'Maintained and developed features for existing apps',
      'Designed, initiated, and developed a new DoctorApp project for YesDok',
    ],
    techStack: ['Android', 'Kotlin'],
  },
  {
    id: 6,
    company: 'Do-It',
    position: 'Fullstack Android Developer',
    period: 'September 2019 - July 2020',
    duration: '11 months',
    location: 'Greater Jakarta Area, Indonesia',
    achievements: [
      'Developed and maintained Android apps with more than 1 million downloads',
      'Implemented new Register/Login feature for Do-it apps',
      'Implemented new payment method using OVO',
      'Participated in Backend (Spring) and FrontEnd (vue.js/html) Development',
    ],
    techStack: ['Android', 'Kotlin', 'Spring', 'Vue.js'],
  },
  {
    id: 7,
    company: 'Self-Employed',
    position: 'Android Developer',
    period: 'September 2016 - August 2019',
    duration: '3 years',
    location: 'Medan, Indonesia',
    achievements: [
      'Worked on various projects: Maps & Navigation Apps, Ticket Booking Apps, Reminder Apps, Shopping Apps',
    ],
    techStack: ['Android', 'Java', 'Kotlin'],
  },
  {
    id: 8,
    company: 'Mashara',
    position: 'Android Developer',
    period: 'November 2017 - February 2019',
    duration: '1 year 4 months',
    location: 'Medan, Indonesia',
    achievements: [
      'Developed reminder apps for Mashara Android (Praying Times)',
      'Maintained apps to support various versions and device sizes',
      'Fixed bugs and worked with team to implement upcoming features',
    ],
    techStack: ['Android', 'Java'],
  },
  {
    id: 9,
    company: 'Universitas Sumatera Utara',
    position: 'Laboratory Assistant',
    period: 'September 2016 - August 2017',
    duration: '1 year',
    location: 'Medan, Indonesia',
    achievements: [
      'Taught Mobile Programming, Basic Concept of OOP and Computer Graphic',
    ],
    techStack: ['Java', 'OOP'],
  },
]

export const skills: Skill[] = [
  // Mobile Development
  { id: 1, name: 'Mobile Application Development', category: 'mobile' },
  { id: 2, name: 'Android Framework', category: 'mobile' },
  { id: 3, name: 'Mobile Product Development', category: 'mobile' },
  { id: 4, name: 'Kotlin', category: 'mobile' },
  { id: 5, name: 'Java', category: 'mobile' },
  { id: 6, name: 'Flutter', category: 'mobile' },
  // Backend Technologies
  { id: 7, name: 'Golang', category: 'backend' },
  { id: 8, name: 'PostgreSQL', category: 'backend' },
  { id: 9, name: 'gRPC', category: 'backend' },
  { id: 10, name: 'Microservices Architecture', category: 'backend' },
  { id: 11, name: 'Redis', category: 'backend' },
  { id: 12, name: 'Apache Kafka', category: 'backend' },
  { id: 13, name: 'Spring Boot', category: 'backend' },
  { id: 14, name: 'REST API Design', category: 'backend' },
  { id: 15, name: 'System Design', category: 'backend' },
  { id: 16, name: 'Performance Optimization', category: 'backend' },
  // DevOps & Infrastructure
  { id: 17, name: 'Docker', category: 'devops' },
  { id: 18, name: 'Kubernetes', category: 'devops' },
  { id: 19, name: 'CI/CD Pipelines', category: 'devops' },
  { id: 20, name: 'GitHub Actions', category: 'devops' },
  { id: 21, name: 'AWS/GCP Cloud', category: 'devops' },
  { id: 22, name: 'Monitoring & Observability', category: 'devops' },
  { id: 23, name: 'Unit & Integration Testing', category: 'devops' },
  { id: 24, name: 'Infrastructure as Code', category: 'devops' },
  // Other Technologies
  { id: 25, name: 'Vue.js', category: 'other' },
  { id: 26, name: 'TypeScript', category: 'other' },
  { id: 27, name: 'Python', category: 'other' },
]

export const projects: Project[] = [
  {
    id: 1,
    name: 'MyPopularMoviesApps',
    description: 'Movie discovery app with offline caching and personalized recommendations. Implemented RESTful API integration, image optimization, and smooth pagination.',
    url: 'https://github.com/Rockerdx/MyPopularMoviesApps',
    tech: ['Java', 'Android', 'REST API', 'SQLite'],
    highlighted: true,
    category: 'Android',
  },
  {
    id: 2,
    name: 'FlutterPopularMoviesApp',
    description: 'Cross-platform movie discovery application built with Flutter. Features real-time API sync, responsive UI, and optimized state management.',
    url: 'https://github.com/Rockerdx/FlutterPopularMoviesApp',
    tech: ['Dart', 'Flutter', 'TheMovieDB API'],
    highlighted: true,
    category: 'Android',
  },
  {
    id: 3,
    name: 'KlinikApp',
    description: 'Healthcare appointment booking system connecting patients with nearby clinics. Implemented GPS-based clinic discovery and real-time availability checking.',
    url: 'https://github.com/Rockerdx/KlinikApp',
    tech: ['Java', 'Android', 'Google Maps API'],
    highlighted: true,
    category: 'Android',
  },
  {
    id: 4,
    name: 'DeepLearningOnAndroid',
    description: 'Educational resource for deploying TensorFlow Lite models on Android. Demonstrates image classification and model optimization for mobile.',
    url: 'https://github.com/Rockerdx/DeepLearningOnAndroid',
    tech: ['Python', 'TensorFlow Lite', 'Android'],
    highlighted: true,
    category: 'Android',
  },
  {
    id: 5,
    name: 'myJNEApps',
    description: 'Logistics app enabling customers to schedule package pickups without visiting JNE offices. Features address autocomplete and delivery tracking.',
    url: 'https://github.com/Rockerdx/myJNEApps',
    tech: ['Java', 'Android', 'Logistics API'],
    category: 'Android',
  },
  {
    id: 6,
    name: 'Temperature',
    description: 'Lightweight Android library for temperature unit conversions. Published as open-source package with comprehensive documentation.',
    url: 'https://github.com/Rockerdx/Temperature',
    tech: ['Kotlin', 'Android', 'Library'],
    category: 'Android',
  },
]

export const education: Education[] = [
  {
    id: 1,
    institution: 'Universitas Sumatera Utara',
    degree: "Bachelor's degree, Computer Science",
    period: '2013 - 2019',
  },
]

export const certifications: Certification[] = [
  { id: 1, name: 'Binar Academy Facilitators' },
  { id: 2, name: 'Bangkit Academy Instructor and Mentor' },
]

// Static fallback for GitHub stats
export const githubStats: GitHubStats = {
  username: 'Rockerdx',
  totalContributions: 1247,
  currentStreak: 12,
  longestStreak: 28,
  totalStars: 145,
  totalForks: 23,
  topLanguages: [
    { name: 'Kotlin', percentage: 42, color: '#A97BFF' },
    { name: 'Java', percentage: 28, color: '#b07219' },
    { name: 'Go', percentage: 15, color: '#00ADD8' },
    { name: 'TypeScript', percentage: 8, color: '#3178c6' },
    { name: 'Python', percentage: 7, color: '#3572A5' },
  ],
  recentRepos: [
    {
      id: 1,
      name: 'vibe-profile-site',
      description: 'Personal portfolio website built with Next.js',
      url: 'https://github.com/Rockerdx/vibe-profile-site',
      stars: 12,
      forks: 2,
      language: 'TypeScript',
      updatedAt: '2026-03-28T10:30:00Z',
    },
    {
      id: 2,
      name: 'MyPopularMoviesApps',
      description: 'Movie discovery application for Udacity',
      url: 'https://github.com/Rockerdx/MyPopularMoviesApps',
      stars: 45,
      forks: 12,
      language: 'Java',
      updatedAt: '2026-02-15T08:20:00Z',
    },
    {
      id: 3,
      name: 'FlutterPopularMoviesApp',
      description: 'Flutter movie app with TheMovieDB API',
      url: 'https://github.com/Rockerdx/FlutterPopularMoviesApp',
      stars: 23,
      forks: 5,
      language: 'Dart',
      updatedAt: '2026-01-20T14:10:00Z',
    },
    {
      id: 4,
      name: 'DeepLearningOnAndroid',
      description: 'Deep learning deployment on mobile',
      url: 'https://github.com/Rockerdx/DeepLearningOnAndroid',
      stars: 38,
      forks: 8,
      language: 'Python',
      updatedAt: '2025-12-10T09:45:00Z',
    },
    {
      id: 5,
      name: 'KlinikApp',
      description: 'Clinic reservation booking app',
      url: 'https://github.com/Rockerdx/KlinikApp',
      stars: 15,
      forks: 3,
      language: 'Java',
      updatedAt: '2025-11-05T16:30:00Z',
    },
    {
      id: 6,
      name: 'Temperature',
      description: 'Android temperature library',
      url: 'https://github.com/Rockerdx/Temperature',
      stars: 12,
      forks: 3,
      language: 'Kotlin',
      updatedAt: '2025-10-20T11:25:00Z',
    },
  ],
}

// Backend Systems Showcase - Professional work at Stockbit
export const backendSystems = [
  {
    id: 1,
    name: 'Issuer (Emitten) RPC Service Optimization',
    description: 'Core financial service providing real-time issuer/company data to the Stockbit platform. Optimized for high-frequency access when users view stock details.',
    challenge: 'High latency (250ms avg) causing slow page loads for 1M+ daily active users viewing issuer information',
    solution: 'Implemented multi-layer caching strategy using Redis in-memory cache with cache-aside pattern, reducing database load and response time',
    impact: [
      'Reduced response latency by 80% (250ms → 50ms)',
      'Decreased PostgreSQL load by 65% during market hours',
      'Improved user experience for stock detail pages',
    ],
    tech: ['Golang', 'gRPC', 'Redis', 'PostgreSQL', 'Microservices'],
    architecture: 'gRPC-based microservice with Redis caching layer',
  },
  {
    id: 2,
    name: 'Watchlist Portfolio Sync Infrastructure',
    description: 'Event-driven system synchronizing user watchlist data across devices and handling real-time portfolio updates for Indonesia stock market users.',
    challenge: '500,000+ events per minute during market open hours, watchlist loaded every time users open the app (homepage feature)',
    solution: 'Built Kafka-based event streaming architecture with async processing, batching, and deduplication to handle high throughput',
    impact: [
      'Successfully handle 500K events/minute at peak',
      'Sub-second sync latency across 1M+ user devices',
      'Zero data loss with Kafka persistence and replay capability',
    ],
    tech: ['Apache Kafka', 'Golang', 'PostgreSQL', 'Event-Driven Architecture'],
    architecture: 'Async event streaming with Kafka topics and consumer groups',
  },
  {
    id: 3,
    name: 'KV2 Configuration Management System',
    description: 'Secure configuration management system for credentials and dynamic config across all Stockbit financial services.',
    challenge: 'Hardcoded credentials, manual config updates requiring deployment, no audit trail or versioning for financial compliance',
    solution: 'Designed KV2 scheme with encryption at rest, versioning, dynamic updates via API, and comprehensive audit logging',
    impact: [
      'Eliminated hardcoded credentials across 15+ services',
      'Enabled zero-downtime configuration updates',
      'Full versioning and audit trail for compliance',
      'Secure handling of API keys, database credentials, and third-party tokens',
    ],
    tech: ['Golang', 'PostgreSQL', 'Encryption', 'Vault Pattern'],
    architecture: 'Centralized config service with encryption and versioning',
  },
  {
    id: 4,
    name: 'IDX Symbol Migration Planning',
    description: 'Strategic migration to transition issuer symbol system from internal Stockbit database to Indonesia Stock Exchange (IDX) as the authoritative source.',
    challenge: 'Complex coordination required between Stockbit tech teams and IDX financial teams (source of truth for all issuer data), zero-downtime migration needed',
    solution: 'Created comprehensive migration plan including data mapping, dual-write strategy, validation procedures, rollback plans, and stakeholder communication framework',
    impact: [
      'Designed migration plan for 800+ issuer symbols',
      'Zero-downtime transition strategy with dual-write phase',
      'Coordination framework for tech and financial teams',
      'Risk mitigation with comprehensive rollback procedures',
    ],
    tech: ['System Design', 'Data Migration', 'Project Planning', 'PostgreSQL'],
    architecture: 'Dual-write migration pattern with validation and rollback',
  },
] as const
